export const projects = [
  {
    title: 'Bloodlink',
    description: "Using Flutter for frontend and Node,Express and Mongo for backend. Me and my teammates created bloodlink for Bloodlink,LCSS as part of our Software Engineering course.",
      image: '/images/1.png',
      tags: ['Mongo', 'Express', 'Flutter', 'Node'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 0,
  },
  {
    title: 'Video Object Detection',
    description:"Video Object Detection is an evergoing field, working on YoloV5 and adding Seq-nms for post-processing we manaaged to improve accuracy of the model. This was our project for Deep Learning course.",
    image: '',
    tags: ['Pytorch'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 1,
  },
  {
    title: 'ML project',
    description: "ML project",
      image: '',
      tags: ['Pytorch'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 2,
  },
  {
    title: 'SP project',
    description: "Sp project",
    image: '',
    tags: ['Pytorch'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 3,
  },
  {
    title: 'Ludo',
    description: "Ludo",
    image: '',
    tags: ['C++'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 4,
  },
  {
    title: 'Chat application',
    description: "Netcen",
    image: '',
    tags: ['Python'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 5,
  },
  {
    title: 'Wordle',
    description: "MERN",
    image: '/images/4.jpg',
    tags: ['MongoDB', 'Express.js', 'Node.js', 'React.js'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 6,
  },
  {
    title: 'Swap-it',
    description: "MERN",
    image: '/images/4.jpg',
    tags: ['MongoDB', 'Express.js', 'Node.js', 'React.js'],
    source: 'https://google.com',
    visit: 'https://google.com',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Created my first website using HTML and CSS', },
  { year: 2019, text: 'Started my BSCS and learnt C++', },
  { year: 2020, text: 'Started learning networks and Algorithms', },
  { year: 2021, text: 'Worked on my first Machine Learning model', },
  { year: 2022, text: 'Started working on Computer Vision Models', },
];